---
development:
  cloud_name: bawden
  api_key: '871835837538431'
  api_secret: 0UX9lb99di7bMCixJNHggFaETD0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: bawden
  api_key: '871835837538431'
  api_secret: 0UX9lb99di7bMCixJNHggFaETD0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: bawden
  api_key: '871835837538431'
  api_secret: 0UX9lb99di7bMCixJNHggFaETD0
  enhance_image_tag: true
  static_file_support: false
